flags: {}
packages:
- '.'
- '../reflex'
- '../ghcjs-dom'
extra-deps:
- StateVar-1.1.0.1
- adjunctions-4.2.2
- base-orphans-0.4.4
- bifunctors-5
- comonad-4.2.7.2
- contravariant-1.3.3
- cpphs-1.19.3
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dependent-map-0.1.1.3
- dependent-sum-0.2.1.0
- distributive-0.4.4
- exception-transformers-0.4.0.1
- exceptions-0.8.0.2
- free-4.12.1
- ghcjs-dom-0.2.1.0
- haskell-src-exts-1.16.0.1
- haskell-src-meta-0.6.0.10
- kan-extensions-4.2.3
- lens-4.13
- nats-1
- polyparse-1.11
- prelude-extras-0.4.0.2
- profunctors-5.1.1
- ref-tf-0.4
- reflection-2.1
- safe-0.3.9
- semigroupoids-5.0.0.4
- semigroups-0.16.2.2
- tagged-0.8.1
- th-expand-syns-0.3.0.6
- th-lift-0.7.2
- th-orphans-0.12.2
- th-reify-many-0.1.3
- these-0.6.0.0
- transformers-compat-0.4.0.4
- void-0.7.1
- dependent-sum-template-0.0.0.4
- th-extras-0.0.0.2
resolver: ghcjs-0.2.0_ghc-7.10.2
